# Generated by Django 3.2 on 2021-04-14 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('discount_rate', models.DecimalField(decimal_places=3, max_digits=18)),
                ('store_method', models.CharField(max_length=10, null=True)),
                ('capacity', models.IntegerField()),
                ('kcal', models.IntegerField()),
                ('is_new', models.BooleanField()),
            ],
            options={
                'db_table': 'product_details',
            },
        ),
        migrations.CreateModel(
            name='Product_detail_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'product_detail_images',
            },
        ),
        migrations.CreateModel(
            name='Product_inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('is_public', models.BooleanField()),
                ('classification', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('insert_at', models.DateTimeField(auto_now_add=True)),
                ('is_answered', models.BooleanField()),
                ('answer', models.TextField(null=True)),
            ],
            options={
                'db_table': 'product_inquiries',
            },
        ),
        migrations.CreateModel(
            name='Product_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=45)),
                ('content', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'product_reviews',
            },
        ),
        migrations.CreateModel(
            name='Product_review_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500)),
                ('product_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.product_review')),
            ],
            options={
                'db_table': 'product_review_images',
            },
        ),
    ]
