# Generated by Django 3.2 on 2021-04-16 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_sub_category_product_category'),
        ('members', '0003_auto_20210416_0649'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_detail',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='post_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='reciever_message',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='reciever_name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='reciever_number',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='reciever_phone_number',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_email',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_phone_number',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productoption'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
