# Generated by Django 3.2 on 2021-04-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('address_detail', models.CharField(max_length=300)),
                ('post_number', models.IntegerField()),
            ],
            options={
                'db_table': 'destinations',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=50)),
                ('date_birth', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('coupon', models.ManyToManyField(related_name='coupon', through='coupons.Member_coupon', to='coupons.Coupon')),
            ],
            options={
                'db_table': 'members',
            },
        ),
    ]
