# Generated by Django 3.2 on 2021-04-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20210416_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_birth',
            field=models.DateField(),
        ),
    ]
